# Generated by Django 5.2.7 on 2025-11-03 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(choices=[('mother_maiden_name', "What is your mother's maiden name?"), ('first_pet_name', 'What was the name of your first pet?'), ('birth_city', 'In which city were you born?'), ('favorite_teacher', 'Who was your favorite teacher?'), ('favorite_book', 'What is your favorite book?'), ('favorite_food', 'What is your favorite food?'), ('childhood_nickname', 'What was your childhood nickname?'), ('first_school_name', 'What was the name of your first school?'), ('favorite_movie', 'What is your favorite movie?'), ('dream_job', 'What was your dream job as a child?'), ('first_car', 'What was the make of your first car?'), ('favorite_sport', 'What is your favorite sport?'), ('favorite_vacation_place', 'What is your favorite vacation place?'), ('best_friend_name', 'What is the first name of your best friend?'), ('favorite_color', 'What is your favorite color?'), ('favorite_subject', 'What was your favorite subject in school?'), ('grandmother_first_name', 'What is your grandmother’s first name?'), ('childhood_street', 'What street did you grow up on?'), ('favorite_singer', 'Who is your favorite singer or musician?'), ('favorite_game', 'What is your favorite game?')], max_length=50)),
                ('answer', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
